version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: 
          command: |
            mkdir out
            echo "test" > out/binary
      - persist_to_workspace:
          root: .
          paths: 
            - out/
  release:
    docker:
      - image: cibuilds/github:0.10
    environment:
      GITHUB_API: https://github.sec.samsung.net/api/v3/
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_BUILD_NUM}
            ARTIFACT_PATH=/tmp/artifacts/out
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} $ARTIFACT_PATH
workflows:
  version: 2
  build_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
